<template>
  <div class="agent-growth">
    <!-- 统计概览 -->
    <div class="growth-stats">
      <div class="stat-card">
        <div class="stat-val">{{ stats.total }}</div>
        <div class="stat-lbl">总任务</div>
      </div>
      <div class="stat-card">
        <div class="stat-val" style="color:#22c55e">{{ stats.success }}</div>
        <div class="stat-lbl">成功</div>
      </div>
      <div class="stat-card">
        <div class="stat-val" style="color:#ef4444">{{ stats.failure }}</div>
        <div class="stat-lbl">失败</div>
      </div>
      <div class="stat-card">
        <div class="stat-val" style="color:#4fc3f7">{{ stats.successRate }}</div>
        <div class="stat-lbl">成功率</div>
      </div>
      <div class="stat-card">
        <div class="stat-val" style="color:#f59e0b">{{ skills.length }}</div>
        <div class="stat-lbl">已习得技能</div>
      </div>
    </div>

    <!-- 技能列表 -->
    <div class="adv-section">
      <div class="section-bar">
        <h4 class="adv-section-title">🧠 已习得技能</h4>
        <el-button size="small" type="primary" @click="showAddSkill = true">添加技能</el-button>
      </div>
      <div v-if="skills.length === 0" class="adv-empty">暂无习得技能</div>
      <div v-for="sk in skills" :key="sk.id" class="skill-card" :class="{ 'skill-auto': sk.autoGenerated }">
        <div class="skill-card-header">
          <span class="skill-name">{{ sk.name }}</span>
          <span v-if="sk.autoGenerated" class="skill-badge-auto">自动</span>
          <span class="skill-confidence">{{ (sk.confidence * 100).toFixed(0) }}%</span>
        </div>
        <div class="skill-desc">{{ sk.description }}</div>
        <div class="skill-meta">
          <span>使用 {{ sk.useCount || 0 }} 次</span>
          <span v-if="sk.trigger">触发: {{ sk.trigger.slice(0, 30) }}{{ sk.trigger.length > 30 ? '...' : '' }}</span>
        </div>
        <div class="skill-actions">
          <el-button size="small" text type="danger" @click="handleDeleteSkill(sk.id)">删除</el-button>
        </div>
      </div>
    </div>

    <!-- 建议列表 -->
    <div class="adv-section">
      <div class="section-bar">
        <h4 class="adv-section-title">💡 主动建议</h4>
        <el-button size="small" @click="loadAnomalies">🔍 异常检测</el-button>
      </div>
      <div v-if="suggestions.length === 0 && anomalies.length === 0" class="adv-empty">暂无建议</div>
      <!-- 异常告警 -->
      <div v-for="a in anomalies" :key="a.title" class="suggestion-card sug-anomaly">
        <div class="sug-type">{{ a.type }}</div>
        <div class="sug-title">{{ a.title }}</div>
        <div class="sug-desc">{{ a.description }}</div>
        <div class="sug-confidence">置信度: {{ (a.confidence * 100).toFixed(0) }}%</div>
      </div>
      <!-- 常规建议 -->
      <div v-for="s in suggestions" :key="s.id" class="suggestion-card" :class="{ 'sug-read': s.read }">
        <div class="sug-type">{{ s.type }}</div>
        <div class="sug-title">{{ s.title }}</div>
        <div class="sug-desc">{{ s.description }}</div>
        <div class="sug-footer">
          <span class="sug-confidence">{{ (s.confidence * 100).toFixed(0) }}%</span>
          <span class="sug-date">{{ s.timestamp?.slice(0, 16).replace('T', ' ') }}</span>
          <div class="sug-actions">
            <el-button v-if="!s.read" size="small" text @click="handleMarkRead(s.id)">标记已读</el-button>
            <el-button v-if="!s.applied" size="small" text type="primary" @click="handleMarkApplied(s.id)">应用</el-button>
            <el-button size="small" text type="danger" @click="handleDeleteSuggestion(s.id)">删除</el-button>
          </div>
        </div>
      </div>
    </div>

    <!-- 经验列表 -->
    <div class="adv-section">
      <div class="section-bar">
        <h4 class="adv-section-title">📜 任务经验</h4>
      </div>
      <div v-if="experiences.length === 0" class="adv-empty">暂无执行经验</div>
      <div v-for="exp in experiences" :key="exp.id" class="exp-card">
        <div class="exp-header">
          <span class="exp-goal">{{ exp.goal.slice(0, 60) }}{{ exp.goal.length > 60 ? '...' : '' }}</span>
          <span class="exp-outcome" :class="exp.success ? 'outcome-success' : 'outcome-fail'">{{ exp.success ? '成功' : '失败' }}</span>
        </div>
        <div v-if="exp.lesson" class="exp-lesson">📝 {{ exp.lesson }}</div>
        <div class="exp-meta">
          <span>{{ exp.timestamp?.slice(0, 16).replace('T', ' ') }}</span>
          <span v-if="exp.duration">耗时 {{ (exp.duration / 1000).toFixed(1) }}s</span>
        </div>
      </div>
    </div>

    <!-- 添加技能对话框 -->
    <el-dialog v-model="showAddSkill" title="添加技能" width="460px" append-to-body>
      <div style="display:flex;flex-direction:column;gap:10px">
        <el-input v-model="skillForm.name" placeholder="技能名称" size="small" />
        <el-input v-model="skillForm.description" type="textarea" :rows="3" placeholder="描述" size="small" />
        <el-input v-model="skillForm.trigger" placeholder="触发关键词" size="small" />
      </div>
      <template #footer>
        <el-button @click="showAddSkill = false">取消</el-button>
        <el-button type="primary" @click="handleAddSkill" :loading="skillSaving">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import { agentGetExperiences, agentGetExperienceStats, agentGetSkills, agentAddSkill, agentDeleteSkill, agentGetSuggestions, agentMarkSuggestionRead, agentMarkSuggestionApplied, agentDeleteSuggestion, agentDetectAnomalies } from '@/api'

const stats = ref({ total: 0, success: 0, failure: 0, successRate: '0%', lessons: [] as string[], topGoals: [] as any[] })
const experiences = ref<any[]>([])
const skills = ref<any[]>([])
const suggestions = ref<any[]>([])
const anomalies = ref<any[]>([])
const showAddSkill = ref(false)
const skillSaving = ref(false)
const skillForm = ref({ name: '', description: '', trigger: '' })

onMounted(() => { loadAll() })

async function loadAll() {
  await Promise.all([loadStats(), loadExperiences(), loadSkills(), loadSuggestions()])
}

async function loadStats() {
  try {
    const res = await agentGetExperienceStats()
    if (res.code === 200) stats.value = res.data
  } catch {}
}

async function loadExperiences() {
  try {
    const res = await agentGetExperiences(20)
    if (res.code === 200) experiences.value = res.data || []
  } catch {}
}

async function loadSkills() {
  try {
    const res = await agentGetSkills()
    if (res.code === 200) skills.value = res.data || []
  } catch {}
}

async function loadSuggestions() {
  try {
    const res = await agentGetSuggestions(20)
    if (res.code === 200) suggestions.value = res.data || []
  } catch {}
}

async function loadAnomalies() {
  try {
    const res = await agentDetectAnomalies()
    if (res.code === 200 && res.data?.length > 0) {
      anomalies.value = res.data
      ElMessage.info(`检测到 ${res.data.length} 个异常`)
    } else {
      ElMessage.success('未检测到异常')
    }
  } catch {}
}

async function handleAddSkill() {
  if (!skillForm.value.name) { ElMessage.warning('请输入技能名称'); return }
  skillSaving.value = true
  try {
    const res = await agentAddSkill({ name: skillForm.value.name, description: skillForm.value.description, trigger: skillForm.value.trigger })
    if (res.code === 200) {
      ElMessage.success('技能添加成功')
      showAddSkill.value = false
      skillForm.value = { name: '', description: '', trigger: '' }
      loadSkills()
    } else { ElMessage.error(res.message) }
  } catch { ElMessage.error('添加失败') }
  finally { skillSaving.value = false }
}

async function handleDeleteSkill(id: string) {
  try {
    const res = await agentDeleteSkill(id)
    if (res.code === 200) { ElMessage.success('已删除'); loadSkills() }
    else { ElMessage.error(res.message) }
  } catch { ElMessage.error('删除失败') }
}

async function handleMarkRead(id: string) {
  try {
    await agentMarkSuggestionRead(id)
    loadSuggestions()
  } catch {}
}

async function handleMarkApplied(id: string) {
  try {
    await agentMarkSuggestionApplied(id)
    ElMessage.success('已标记为已应用')
    loadSuggestions()
  } catch {}
}

async function handleDeleteSuggestion(id: string) {
  try {
    await agentDeleteSuggestion(id)
    loadSuggestions()
  } catch {}
}
</script>

<style scoped>
.agent-growth { display: flex; flex-direction: column; gap: 16px; }
.growth-stats { display: grid; grid-template-columns: repeat(5, 1fr); gap: 8px; }
.stat-card { background: rgba(255,255,255,0.02); border: 1px solid rgba(255,255,255,0.06); border-radius: 8px; padding: 12px; text-align: center; }
.stat-val { font-size: 22px; font-weight: 700; color: #e2e8f0; }
.stat-lbl { font-size: 11px; color: #64748b; margin-top: 2px; }

.skill-card { background: rgba(255,255,255,0.02); border: 1px solid rgba(255,255,255,0.06); border-radius: 8px; padding: 12px; margin-bottom: 8px; }
.skill-card.skill-auto { border-color: rgba(79,195,247,0.2); }
.skill-card-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px; }
.skill-name { font-size: 13px; font-weight: 500; color: #e2e8f0; }
.skill-badge-auto { font-size: 10px; padding: 1px 6px; background: rgba(79,195,247,0.15); color: #4fc3f7; border-radius: 3px; }
.skill-confidence { font-size: 12px; color: #4fc3f7; }
.skill-desc { font-size: 12px; color: #94a3b8; margin-bottom: 6px; }
.skill-meta { display: flex; gap: 12px; font-size: 11px; color: #64748b; margin-bottom: 4px; }
.skill-actions { display: flex; gap: 4px; }

.suggestion-card { background: rgba(255,255,255,0.02); border: 1px solid rgba(255,255,255,0.06); border-radius: 8px; padding: 12px; margin-bottom: 8px; }
.suggestion-card.sug-anomaly { border-color: rgba(239,68,68,0.2); background: rgba(239,68,68,0.03); }
.suggestion-card.sug-read { opacity: 0.6; }
.sug-type { font-size: 10px; color: #4fc3f7; text-transform: uppercase; margin-bottom: 4px; }
.sug-anomaly .sug-type { color: #ef4444; }
.sug-title { font-size: 13px; color: #e2e8f0; font-weight: 500; margin-bottom: 4px; }
.sug-desc { font-size: 12px; color: #94a3b8; margin-bottom: 8px; }
.sug-footer { display: flex; align-items: center; gap: 12px; font-size: 11px; }
.sug-confidence { color: #4fc3f7; }
.sug-date { color: #475569; }
.sug-actions { margin-left: auto; display: flex; gap: 4px; }

.exp-card { background: rgba(255,255,255,0.02); border: 1px solid rgba(255,255,255,0.06); border-radius: 8px; padding: 10px; margin-bottom: 6px; }
.exp-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 4px; }
.exp-goal { font-size: 12px; color: #e2e8f0; }
.exp-outcome { font-size: 10px; padding: 1px 6px; border-radius: 3px; }
.outcome-success { background: rgba(34,197,94,0.15); color: #22c55e; }
.outcome-fail { background: rgba(239,68,68,0.15); color: #ef4444; }
.exp-lesson { font-size: 11px; color: #f59e0b; margin-bottom: 4px; padding: 4px 8px; background: rgba(245,158,11,0.05); border-radius: 4px; }
.exp-meta { display: flex; gap: 12px; font-size: 10px; color: #475569; }
</style>
